sonar.projectKey=cleanproject
sonar.working.directory=/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/.sonar
sonar.projectBaseDir=/Users/aziztayebi/Documents/net projects/cleanproject
sonar.pullrequest.cache.basepath=/Users/aziztayebi/Documents/net projects/cleanproject
sonar.sources=\
"/Users/aziztayebi/Documents/net projects/cleanproject/docker-compose.yml"

9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.projectKey=cleanproject:9C58F355-A750-F264-F3C8-3C1E0A501BF2
9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.projectName=MySolution.Domain
9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.projectBaseDir=/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain
9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.sourceEncoding=utf-8
9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.tests=
9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.sources=\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain/Clients/Clients.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain/Clients/IClientRepository.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain/Orders/IOrderRepository.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain/Orders/Order.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain/obj/MySolution.Domain.csproj.nuget.dgspec.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain/obj/project.assets.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Domain/bin/Debug/net10.0/MySolution.Domain.deps.json"

9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.cs.analyzer.projectOutPaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/0",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/5"
9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.cs.roslyn.reportFilePaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/0/Issues.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/5/Issues.json"
9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.cs.scanner.telemetry=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/0/Telemetry.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/5/Telemetry.json"

9C58F355-A750-F264-F3C8-3C1E0A501BF2.sonar.working.directory=/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/.sonar/mod0
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.projectKey=cleanproject:4AA9FB77-EFA9-A5D1-308E-31671C679EE8
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.projectName=MySolution.Tests
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.projectBaseDir=/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.sourceEncoding=utf-8
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.sources=
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.tests=\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/obj/MySolution.Tests.csproj.nuget.dgspec.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/obj/project.assets.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/bin/Debug/net10.0/MySolution.Tests.runtimeconfig.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/bin/Debug/net10.0/MySolution.Tests.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/GetOrderByIdHandlerTests.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/UpdateDescriptionOrderHandlerTests.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/coverage.opencover.xml",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Tests/TestResults/854ab53b-6b41-4e29-b584-27d5e9fd6cd2/coverage.cobertura.xml"

4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.cs.analyzer.projectOutPaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/7",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/3"
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.cs.roslyn.reportFilePaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/7/Issues.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/3/Issues.json"
4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.cs.scanner.telemetry=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/7/Telemetry.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/3/Telemetry.json"

4AA9FB77-EFA9-A5D1-308E-31671C679EE8.sonar.working.directory=/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/.sonar/mod1
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.projectKey=cleanproject:A3531EE0-53D4-71DB-2AEC-18ED60CDED08
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.projectName=MySolution.Application
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.projectBaseDir=/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.sourceEncoding=utf-8
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.tests=
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.sources=\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/obj/MySolution.Application.csproj.nuget.dgspec.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/obj/project.assets.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/bin/Debug/net10.0/MySolution.Application.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Common/Exceptions/NotFoundException.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Orders/Commands/CreateOrderCommand.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Orders/Commands/CreateOrderHandler.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Orders/Commands/UpdateDescriptionOrderCommand.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Orders/Commands/UpdateDescriptionOrderHandler.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Orders/DTOs/OrderDto.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Orders/Queries/GetOrderByIdHandler.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Application/Orders/Queries/GetOrderByIdQuery.cs"

A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.cs.analyzer.projectOutPaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/6",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/2"
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.cs.roslyn.reportFilePaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/6/Issues.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/2/Issues.json"
A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.cs.scanner.telemetry=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/6/Telemetry.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/2/Telemetry.json"

A3531EE0-53D4-71DB-2AEC-18ED60CDED08.sonar.working.directory=/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/.sonar/mod2
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.projectKey=cleanproject:5FBA7560-B57B-27F4-392F-04FFC15A09A3
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.projectName=MySolution.Infrastructure
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.projectBaseDir=/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.sourceEncoding=utf-8
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.tests=
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.sources=\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/obj/MySolution.Infrastructure.csproj.nuget.dgspec.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/obj/project.assets.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/bin/Debug/net10.0/MySolution.Infrastructure.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/bin/Debug/net10.0/MySolution.Infrastructure.runtimeconfig.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/bin\\Debug/net10.0/BuildHost-net472/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/bin\\Debug/net10.0/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/bin\\Debug/net10.0/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/AppDbContext.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/Migrations/20260211194018_InitialCreate.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/Migrations/20260211194018_InitialCreate.Designer.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/Migrations/20260211201438_DescriptionAdded.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/Migrations/20260211201438_DescriptionAdded.Designer.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/Migrations/AppDbContextModelSnapshot.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/Persistence/Clients/ClientRepository.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/Persistence/Orders/OrderRepository.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/bin/Debug/net10.0/MySolution.Domain.pdb",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.Infrastructure/bin/Debug/net10.0/MySolution.Infrastructure.pdb"

5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.cs.analyzer.projectOutPaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/1"
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.cs.roslyn.reportFilePaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/1/Issues.json"
5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.cs.scanner.telemetry=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/1/Telemetry.json"

5FBA7560-B57B-27F4-392F-04FFC15A09A3.sonar.working.directory=/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/.sonar/mod3
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.projectKey=cleanproject:0E003297-AFC3-49F5-852C-9397DEC5691C
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.projectName=MySolution.API
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.projectBaseDir=/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.sourceEncoding=utf-8
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.tests=
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.sources=\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/appsettings.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/appsettings.Development.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/project.assets.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/MySolution.API.csproj.nuget.dgspec.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/Properties/launchSettings.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/staticwebassets.build.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/staticwebassets.build.endpoints.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/rjsmrazor.dswa.cache.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/rjsmcshtml.dswa.cache.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/rpswa.dswa.cache.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/appsettings.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.API.runtimeconfig.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.API.staticwebassets.endpoints.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/appsettings.Development.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.API.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin\\Debug/net10.0/BuildHost-net472/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin\\Debug/net10.0/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin\\Debug/net10.0/BuildHost-netcore/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/appsettings.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/MySolution.API.runtimeconfig.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/MySolution.API.staticwebassets.endpoints.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/appsettings.Development.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/MySolution.API.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/bin/Debug/net10.0/appsettings.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/bin/Debug/net10.0/MySolution.API.runtimeconfig.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/bin/Debug/net10.0/MySolution.API.staticwebassets.endpoints.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/bin/Debug/net10.0/appsettings.Development.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/bin/Debug/net10.0/bin/Debug/net10.0/MySolution.API.deps.json",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/Middleware/ExceptionHandlingMiddleware.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/Orders/OrdersController.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/Program.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/MySolution.API.GlobalUsings.g.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/MySolution.API.AssemblyInfo.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/obj/Debug/net10.0/MySolution.API.MvcApplicationPartsAssemblyInfo.cs",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.API",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.API.pdb",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.Application.pdb",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.Domain.pdb",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/bin/Debug/net10.0/MySolution.Infrastructure.pdb",\
"/Users/aziztayebi/Documents/net projects/cleanproject/MySolution.API/MySolution.API.http"

0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.cs.analyzer.projectOutPaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/4"
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.cs.roslyn.reportFilePaths=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/4/Issues.json"
0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.cs.scanner.telemetry=\
"/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/4/Telemetry.json"

0E003297-AFC3-49F5-852C-9397DEC5691C.sonar.working.directory=/Users/aziztayebi/Documents/net projects/cleanproject/.sonarqube/out/.sonar/mod4
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/bin/**,**/obj/**,**/coverage.opencover.xml
sonar.visualstudio.enable=false

sonar.modules=9C58F355-A750-F264-F3C8-3C1E0A501BF2,4AA9FB77-EFA9-A5D1-308E-31671C679EE8,A3531EE0-53D4-71DB-2AEC-18ED60CDED08,5FBA7560-B57B-27F4-392F-04FFC15A09A3,0E003297-AFC3-49F5-852C-9397DEC5691C

